### ISSUE TITLE
Prettier directory diffs

### ISSUE THREAD

**Issue by SamuelSchlesinger** [SamuelSchlesinger/version-control#5]
Currently, the directory diffs are displayed in prettified JSON and we include the hashes which is totally useless as a reader. Make it prettier and less useless!

**Comment by pete-murphy** [comment]
Haven't fully dug into this project, but interested in looking into this as a way of learning some more Rust 🙂. Would the intent be that `revtool diff` have output like `git diff --name-status`?
```
❯ git diff --name-status pm/9-snap-panics
A       LICENSE
M       README.md
M       app/main.rs
M       src/dot_rev.rs
```

**Comment by SamuelSchlesinger** [comment]
Sounds great! Anything that conveys the information concisely works for me.
