### ISSUE TITLE
`revtool snap` panics

### ISSUE THREAD

**Issue by pete-murphy** [SamuelSchlesinger/version-control#9]
```
Code/rust/foo
❯ revtool init

Code/rust/foo
❯ echo "💩" >> poo.txt

Code/rust/foo
❯ revtool changes
{
  "deleted": [],
  "added": {
    "poo.txt": {
      "File": "9c7ecb3d4acb554df052dbaf031d51987a0ba8970dd858d157bb40aabf9ce948"
    }
  },
  "modified": {}

Code/rust/foo
❯ revtool snap --message "Added poo.txt"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', app/main.rs:53:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think https://github.com/SamuelSchlesinger/version-control/blob/19b9675920cd93fdb472b1b69fb0de6bc4557de7/app/main.rs#L154 might need to use the same `read_to_string` as the `Changes` branch https://github.com/SamuelSchlesinger/version-control/blob/19b9675920cd93fdb472b1b69fb0de6bc4557de7/app/main.rs#L130-L136

I can make that change if that sounds right?

**Comment by SamuelSchlesinger** [comment]
That is right indeed, thanks for catching it. #1 should naturally fix this kind of inconsistency, gotta get to that.
